#!/bin/sh

##---------- Autostart Apps ----------##

# Run Keybindings Daemon
pgrep -x sxhkd >/dev/null || sxhkd &

# Run Polybar
sh $HOME/.config/polybar/polybar.sh

# Run Dunst
dunst --config $HOME/.config/dunst/dunstrc &

# Run polkit daemon if doesn't started
[ -n "$(pidof xfce-polkit)" ] || /usr/lib/xfce-polkit/xfce-polkit &

# Start Wallpaper
feh --bg-fill --no-fehbg --randomize $HOME/Wallpapers/* &

# Autorun
sh $HOME/.local/bin/autorun 

##---------- X Settings ----------##

# Fix Cursor
xsetroot -cursor_name left_ptr &

# Set Resolution
xrandr --output eDP1 --mode 1366x768 --scale 1.0x1.0 --dpi 100

# Set Keyboard Repeat Delay and Rate
xset r rate 200 50

##---------- Window Rules ----------##

bspc monitor -d 1 2 3 4 5 6

# bspc rule -a telegram-desktop desktop=^5 follow=on focus=on

##---------- General Configuration ----------##

bspc config border_width 5
bspc config window_gap 10
bspc config split_ratio 0.5

bspc config normal_border_color "#000000"
bspc config active_border_color "#ffffff"
bspc config focused_border_color "#2da4a4"
bspc config presel_feedback_color "#fd2e59"

bspc config focus_follows_pointer true
bspc config pointer_modifier true
bspc config paddingless_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true
